version: '3.7'
services:
  elasticsearch:
    image: elasticsearch:6.8.13
    container_name: elasticsearch
    restart: always
    environment:
    - xpack.security.enabled=false
    - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
    - IPC_LOCK
    volumes:
    - esdata:/usr/share/elasticsearch/data
    ports:
    - 9200:9200

  jaegercollector:
    image: jaegertracing/jaeger-collector
    container_name: jaegercollector
    restart: always
    environment:
    - SPAN_STORAGE_TYPE=elasticsearch
    - ES_SERVER_URLS=http://elasticsearch:9200
    ports:
    # - 14250:14250
    - 14269:14269
    - 4317:4317
    command:
    - --collector.otlp.enabled=true
    - --log-level=debug
    depends_on:
    - elasticsearch

  jaegeragent:
    image: jaegertracing/jaeger-agent
    container_name: jaegeragent
    restart: always
    ports:
    - 6831:6831
    command:
    - --reporter.grpc.host-port=jaegercollector:14250
    - --log-level=debug
    depends_on:
    - jaegercollector

  jaegerquery:
    image: jaegertracing/jaeger-query
    container_name: jaegerquery
    restart: always
    environment:
    - SPAN_STORAGE_TYPE=elasticsearch
    - ES_SERVER_URLS=http://elasticsearch:9200
    - JAEGER_AGENT_HOST=jaegeragent
    - JAEGER_AGENT_PORT=6831
    ports:
    - 16686:16686
    depends_on:
    - jaegeragent

volumes:
  esdata:
    driver: local