receivers:
  otlp:
    protocols:
      http:

exporters:
  otlphttp:
    endpoint: http://jaeger:4318
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlphttp]
  telemetry:
    logs:
      level: debug